# Generated by Django 5.0 on 2024-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertise_id', models.AutoField(db_column='ADVERTISE_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='DATE')),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=50)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=15, null=True)),
            ],
            options={
                'db_table': 'advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='BOOKING_ID', primary_key=True, serialize=False)),
                ('starting_date', models.DateField(db_column='STARTING_DATE')),
                ('ending_date', models.DateField(db_column='ENDING_DATE')),
                ('time', models.TimeField(db_column='TIME')),
                ('event_name', models.CharField(db_column='EVENT_NAME', max_length=15)),
                ('booking_date', models.DateField(blank=True, db_column='BOOKING_DATE', null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=15, null=True)),
                ('total', models.IntegerField(blank=True, db_column='TOTAL', null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('booking_detail_id', models.AutoField(db_column='BOOKING_DETAIL_ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('amount', models.IntegerField(blank=True, db_column='AMOUNT', null=True)),
            ],
            options={
                'db_table': 'booking_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(db_column='COMMITTEE_ID', primary_key=True, serialize=False)),
                ('work_of_committee', models.CharField(db_column='WORK_OF_COMMITTEE', max_length=30)),
                ('no_of_members', models.IntegerField(db_column='NO._OF_MEMBERS')),
                ('committee_creation_date', models.DateField(db_column='COMMITTEE_CREATION_DATE')),
            ],
            options={
                'db_table': 'committee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeDetails',
            fields=[
                ('committee_detail_id', models.AutoField(db_column='COMMITTEE_DETAIL_ID', primary_key=True, serialize=False)),
                ('member_joining_date', models.DateField(db_column='MEMBER_JOINING_DATE')),
                ('member_leaving_date', models.DateField(blank=True, db_column='MEMBER_LEAVING_DATE', null=True)),
            ],
            options={
                'db_table': 'committee_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(db_column='COMPLAINT_ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=50)),
                ('complaint_date', models.DateField(db_column='COMPLAINT_DATE')),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=15, null=True)),
                ('solution_date', models.DateField(blank=True, db_column='SOLUTION_DATE', null=True)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('deposit_id', models.AutoField(db_column='DEPOSIT_ID', primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, db_column='BANK_NAME', max_length=10, null=True)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
                ('rate', models.IntegerField(db_column='RATE')),
                ('deposit_amount', models.IntegerField(db_column='DEPOSIT_AMOUNT')),
                ('deposit_date', models.DateField(db_column='DEPOSIT_DATE')),
                ('maturity_date', models.DateField(blank=True, db_column='MATURITY_DATE', null=True)),
            ],
            options={
                'db_table': 'deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expence_id', models.AutoField(db_column='EXPENCE_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='DATE')),
                ('amount', models.IntegerField(db_column='AMOUNT')),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=30, null=True)),
            ],
            options={
                'db_table': 'expense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(db_column='FUNCTION_ID', primary_key=True, serialize=False)),
                ('function_name', models.CharField(db_column='FUNCTION_NAME', max_length=30)),
                ('function_place', models.CharField(db_column='FUNCTION_PLACE', max_length=15)),
                ('amount_per_member', models.IntegerField(db_column='AMOUNT_PER_MEMBER')),
                ('date', models.DateField(db_column='DATE')),
            ],
            options={
                'db_table': 'function',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(db_column='INCOME_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='DATE', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='AMOUNT', null=True)),
            ],
            options={
                'db_table': 'income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(db_column='ITEM_ID', primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='ITEM_NAME', max_length=20)),
                ('total_quantity', models.IntegerField(db_column='TOTAL_QUANTITY')),
                ('price_per_unit', models.IntegerField(db_column='PRICE_PER_UNIT')),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(db_column='MAINTENANCE_ID', primary_key=True, serialize=False)),
                ('month_year', models.CharField(db_column='MONTH/YEAR', max_length=30)),
                ('total_income', models.IntegerField(db_column='TOTAL_INCOME')),
                ('total_expence', models.IntegerField(db_column='TOTAL_EXPENCE')),
                ('amount_required', models.IntegerField(db_column='AMOUNT_REQUIRED')),
                ('no_of_member', models.IntegerField(db_column='NO._OF_MEMBER')),
                ('maintenance_amount', models.IntegerField(db_column='MAINTENANCE_AMOUNT')),
                ('last_date', models.DateField(db_column='LAST_DATE')),
                ('late_charges', models.IntegerField(blank=True, db_column='LATE_CHARGES', null=True)),
            ],
            options={
                'db_table': 'maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(db_column='MEMBER_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=20)),
                ('email', models.CharField(db_column='EMAIL', max_length=20)),
                ('password', models.CharField(db_column='PASSWORD', max_length=15)),
                ('contact_no_field', models.BigIntegerField(db_column='CONTACT_NO.')),
                ('flat_no_field', models.IntegerField(db_column='FLAT_NO.')),
                ('block_no_field', models.CharField(db_column='BLOCK_NO.', max_length=1)),
                ('gender', models.CharField(db_column='GENDER', max_length=6)),
                ('religion', models.CharField(blank=True, db_column='RELIGION', max_length=10, null=True)),
                ('house_status', models.CharField(db_column='HOUSE_STATUS', max_length=10)),
                ('member_status', models.CharField(db_column='MEMBER_STATUS', max_length=10)),
                ('comming_date', models.DateField(db_column='COMMING_DATE')),
                ('leaving_date', models.DateField(blank=True, db_column='LEAVING_DATE', null=True)),
                ('family_member', models.IntegerField(blank=True, db_column='FAMILY_MEMBER', null=True)),
                ('profile', models.CharField(blank=True, db_column='PROFILE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberFunction',
            fields=[
                ('member_function_id', models.AutoField(db_column='MEMBER_FUNCTION_ID', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(db_column='AMOUNT')),
                ('pay_date', models.DateField(db_column='PAY_DATE')),
                ('no_of_pass', models.IntegerField(db_column='NO._OF_PASS')),
            ],
            options={
                'db_table': 'member_function',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMaintenance',
            fields=[
                ('member_maintenance_id', models.IntegerField(db_column='MEMBER_MAINTENANCE_ID', primary_key=True, serialize=False)),
                ('pay_date', models.DateField(db_column='PAY_DATE')),
                ('amount', models.IntegerField(db_column='AMOUNT')),
                ('late_charges', models.IntegerField(blank=True, db_column='LATE_CHARGES', null=True)),
                ('total', models.IntegerField(db_column='TOTAL')),
            ],
            options={
                'db_table': 'member_maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(db_column='NOTICE_ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=50)),
                ('date', models.DateField(db_column='DATE')),
                ('status', models.CharField(db_column='STATUS', max_length=15)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('occupant_id', models.AutoField(db_column='OCCUPANT_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=20)),
                ('gender', models.CharField(db_column='GENDER', max_length=6)),
                ('religion', models.CharField(blank=True, db_column='RELIGION', max_length=15, null=True)),
                ('comming_date', models.DateField(db_column='COMMING_DATE')),
                ('rent_amount', models.IntegerField(blank=True, db_column='RENT_AMOUNT', null=True)),
                ('no_of_family_member', models.IntegerField(blank=True, db_column='NO._OF_FAMILY_MEMBER', null=True)),
                ('profile', models.CharField(blank=True, db_column='PROFILE', max_length=100, null=True)),
                ('leaving_date', models.DateField(blank=True, db_column='LEAVING_DATE', null=True)),
            ],
            options={
                'db_table': 'occupant',
                'managed': False,
            },
        ),
    ]
