# Generated by Django 5.0 on 2024-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
