# Generated by Django 5.0.3 on 2024-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
